# -*- coding: utf-8 -*-
"""デザイン総合演習.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G9z_Qno4tHP3Ur41DAHIsPvBi5PcSSSR
"""

# pip install scikit-learn matplotlib scipy fugashi tqdm
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.svm import SVC
from sklearn.svm import LinearSVC
from sklearn.calibration import CalibratedClassifierCV

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import ConfusionMatrixDisplay

import matplotlib.pyplot as plt
from scipy.sparse import hstack

import fugashi
from fugashi import GenericTagger

from tqdm import tqdm

import re
import numpy as np

from sklearn.preprocessing import StandardScaler

tagger = fugashi.GenericTagger('-r "C:\\Program Files\\MeCab\\etc\\mecabrc" -d "C:\\Program Files\\MeCab\\dic\\ipadic"')
df = pd.read_csv(
    "fakenews_012new.csv",
    encoding="utf-8"
)

print(df.head())

# 日本語解析(MeCab)
def mecab_tokenizer(text):
    # 新聞社名を削除
    text = re.sub(
        r"(共同通信|NHK|読売新聞|毎日新聞|朝日新聞|産経新聞|中日新聞|神奈川新聞)",
        "",
        str(text)
    )
    text = re.sub(r"によると?", "", text)
    text = re.sub(r"報道", "", text)

    pbar.update(1)
    tokens = []
    for word in tagger(text):
        pos = word.feature[0]
        surface = word.surface
        # 品詞フィルタ・数字除外・記号除外
        if (
            # surface
            pos in ["名詞", "動詞", "形容詞"]
            # pos == "名詞"
            and len(surface) > 1
            and not re.fullmatch(r'[0-9０-９]+', surface)
            and not re.fullmatch(r'[^\w\u3040-\u30FF\u4E00-\u9FFF]+', surface)):
            tokens.append(surface)
    return tokens


# 独自変数
# ここに定義していく

# "!"の数
def exclamation_count(text):
    return text.count("!")

# 曖昧表現
def ambiguity_count(text):
    ambiguous = [
    "はず",
    "だろう",
    "かもしれない",
    "らしい",
    "とみられる",
    "とのこと",
    "という"
    ]
    return sum(text.count(a) for a in ambiguous)

# 記号の数
def symbol_count(text):
    return len(re.findall(r'[^\w\u3040-\u30FF\u4E00-\u9FFF\s]', text))

# 文の長さ
def text_length(text):
    return len(text)

# 数字の割合
def digit_ratio(text):
    digits = sum(c.isdigit() for c in text)
    return digits / max(len(text),1)

tagger = GenericTagger()

# text = "トヨタは東京都で新車を発表した"
# for word in tagger(text):
    # print(word.surface, word.feature)

# 固有名詞の割合
def proper_noun_ratio(text):
    words = list(tagger(str(text)))

    total = len(words)
    proper = 0

    for word in words:
        features = word.feature

        try:
            if features[0] == "名詞" and features[1] == "固有名詞":
                proper += 1
        except:
            pass

    return proper / total if total > 0 else 0

# 一文の長さの平均
def avg_sentence_length(text):
    sentences = re.split(r'[。！？]', text)
    sentences = [s for s in sentences if s]
    if len(sentences)==0:
        return 0
    return sum(len(s) for s in sentences)/len(sentences)

# 名詞割合
def noun_ratio(text):
    words = list(tagger(str(text)))

    total = len(words)
    noun = 0

    for word in words:
        if word.feature[0] == "名詞":
            noun += 1

    return noun / max(total, 1)

# 文の数
def sentence_count(text):
    return len([s for s in re.split(r'[。！？]', text) if s])

# 漢字率
def kanji_ratio(text):
    kanji = len(re.findall(r'[一-龯]', text))
    return kanji / max(len(text), 1)

# ひらがな率
def hiragana_ratio(text):
    hira = len(re.findall(r'[ぁ-ん]', text))
    return hira / max(len(text), 1)


def report_style_count(text):
    words = [
        "発表", "協議", "協力", "現地",
        "今年", "昨年", "今後", "今回",
        "行った", "開か", "実施", "確認","報道"
    ]
    return sum(text.count(w) for w in words)

def quote_style_count(text):
    words = [
        "によると", "と語った", "と述べた",
        "と発表した", "明らかにした",
        "関係者は", "としている", "とのこと",
        "という"
    ]
    return sum(text.count(w) for w in words)

def person_info_count(text):
    words = [
        "さん", "氏", "出身", "卒業",
        "語った", "述べた", "説明した"
    ]
    return sum(text.count(w) for w in words)


df["exclamation_count"] = df["context"].apply(exclamation_count)
df["ambiguity_count"] = df["context"].apply(ambiguity_count)
df["symbol_count"] = df["context"].apply(symbol_count)
df["text_length"] = df["context"].apply(text_length)
df["digit_ratio"] = df["context"].apply(digit_ratio)
df["proper_noun_ratio"] = df["context"].apply(proper_noun_ratio)
df["avg_sentence_length"] = df["context"].apply(avg_sentence_length) 
df["noun_ratio"] = df["context"].apply(noun_ratio)
df["sentence_count"] = df["context"].apply(sentence_count)
df["kanji_ratio"] = df["context"].apply(kanji_ratio)
df["hiragana_ratio"] = df["context"].apply(hiragana_ratio)
df["report_style_count"] = df["context"].apply(report_style_count)
df["quote_style_count"] = df["context"].apply(quote_style_count)
df["person_info_count"] = df["context"].apply(person_info_count)
# df[""] = df[""].apply()


print(df.groupby("isfake")[[
    "exclamation_count", 
    "ambiguity_count",
    "symbol_count",
    "text_length",
    "digit_ratio",
    "proper_noun_ratio",
    "avg_sentence_length",
    ]].mean())


print("proper_noun_ratio:")
print(df.groupby("isfake")["proper_noun_ratio"].describe())
print("\ndigit_ratio:")
print(df.groupby("isfake")["digit_ratio"].describe())
print("\navg_sentence_length:")
print(df.groupby("isfake")["avg_sentence_length"].describe())
print("\nquote_style_count:")
print(df.groupby("isfake")["quote_style_count"].describe())
print("\nreport_style_count:")
print(df.groupby("isfake")["report_style_count"].describe())


feature_colums = [
    # "exclamation_count",
    # "ambiguity_count",
    "symbol_count",
    "text_length",
    "digit_ratio",
    "proper_noun_ratio",
    "avg_sentence_length",
    "noun_ratio",
    "sentence_count",
    "kanji_ratio",
    "hiragana_ratio",
    "report_style_count",
    "quote_style_count",
    "person_info_count",
    
    # ここに追加
]

x = df["context"]
y     = (df["isfake"] > 0).astype(int)

extra = df[feature_colums]

x_train, x_test, y_train, y_test, extra_train, extra_test = train_test_split(
    x,
    y,
    extra,
    test_size=0.2,
    random_state=42
)

# 独自特徴量を標準化
scaler = StandardScaler()

extra_train_scaled = scaler.fit_transform(extra_train)
extra_test_scaled = scaler.transform(extra_test)

print(df["isfake"].value_counts())
print(y_train.value_counts())
print(y_test.value_counts())


pbar = tqdm(total=len(x_train), desc="MeCab処理")

vectorizer = TfidfVectorizer(
    # n個の単語を数値ベクトル化
    max_features = 20000,
    tokenizer=mecab_tokenizer,
    token_pattern=None,
    # n%以上の記事で出現した単語は除外
    max_df = 0.85,
    # n回以上出現しないと除外
    min_df = 4,
    # nフレーズも抽出できる(1, n)
    ngram_range=(1,2),
    # 出現回数の重みの調節（log）
    sublinear_tf=True
)

x_train_tfidf = vectorizer.fit_transform(x_train)

print(vectorizer.get_feature_names_out())
print(vectorizer.get_feature_names_out()[:50])

x_test_tfidf = vectorizer.transform(x_test)

# print(vectorizer.get_feature_names_out())

# TF-IDFのみの場合はコメントアウト
# x_train_tfidf = hstack((x_train_tfidf, extra_train_scaled))
# x_test_tfidf = hstack((x_test_tfidf, extra_test_scaled))


print(x_train_tfidf.shape)
print(x_test_tfidf.shape)

# print("標準化後の平均")
# print(extra_train_scaled.mean(axis=0))
# print("標準化後の標準偏差")
# print(extra_train_scaled.std(axis=0))

base_model = LinearSVC(
    class_weight="balanced",
    random_state=42,
    # 最適化回数
    max_iter=20000,
    # どれだけ寄せるか≒学習率（大きいほど過学習しやすい0.1～1が目安）
    C=1
)

model = CalibratedClassifierCV(
    base_model,
    # 分割回数（大きいほど処理が遅い）
    cv=3
)

# SVC（処理が遅い）
# model = SVC(kernel="linear", probability=True, class_weight="balanced")

model.fit(x_train_tfidf, y_train)
# 独自特徴量だけ
# model.fit(extra_train_scaled, y_train)

# LinearSVC本体を取り出す
svm_model = model.calibrated_classifiers_[0].estimator

coef_df = pd.DataFrame(
    svm_model.coef_[:, -len(feature_colums):],
    columns=feature_colums,
    index=["Fake"]
)

print(coef_df.T)

coef_fake = pd.Series(
    svm_model.coef_[0, -len(feature_colums):],
    index=feature_colums
)

print(coef_fake.sort_values(ascending=False))


feature_names = vectorizer.get_feature_names_out()

coef = svm_model.coef_[0, :-len(feature_colums)]

top_idx = np.argsort(coef)[-30:]

for i in reversed(top_idx):
    print(feature_names[i], coef[i])

bottom_idx = np.argsort(coef)[:30]

for i in bottom_idx:
    print(feature_names[i], coef[i])

y_pred = model.predict(x_test_tfidf)
# 独自特徴量だけ
# y_pred = model.predict(extra_test_scaled)

print(pd.Series(y_pred).value_counts())
print(model.classes_)

proba = model.predict_proba(x_test_tfidf)
# 独自特徴量だけ
# proba = model.predict_proba(extra_test_scaled)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

fake_score = proba[:, 1]   # クラス3がないので1+2

actual_map = {0: "Real", 1: "Fake"}

for i in range(5):

    print("ニュース本文:")
    print(x_test.iloc[i][:200])
    print()

    if y_pred[i] == 0:
        label = "Real"
    else:
        label = "Fake"

    real_score = round((1 - fake_score[i]) * 100, 2)

    print(f"判定: {label}")
    print(f"信頼度: {real_score}%（0=フェイク、100=リアル）")
    print(f"正解: {actual_map[y_test.iloc[i]]}")
    print("-" * 50)

cm = confusion_matrix(
    y_test,
    y_pred,
    normalize="true"
)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm
)

disp.plot()
plt.savefig("confusion_matrix2.png", dpi=150, bbox_inches="tight")
plt.show()