# -*- coding: utf-8 -*-
"""デザイン総合演習.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G9z_Qno4tHP3Ur41DAHIsPvBi5PcSSSR
"""

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

df = pd.read_csv(
    "fakenews.csv",
    encoding="utf-8"
)

print(df.head())

def exclamation_count(text):
  return text.count("!")

df["exclamation_count"] = df["context"].apply(
    exclamation_count
)

feature_colums = [
    "exclamation_count"
]

x = df["context"]
y = df["isfake"]

extra = df[feature_colums]

x_train, x_test, y_train, y_test, extra_train, extra_test = train_test_split(
    x,
    y,
    extra,
    test_size=0.2,
    random_state=42
)

vectorizer = TfidfVectorizer(
    max_features = 10000
)

x_train_tfidf = vectorizer.fit_transform(x_train)

print(vectorizer.get_feature_names_out())

print(vectorizer.get_feature_names_out()[:50])

x_test_tfidf = vectorizer.transform(x_test)

print(vectorizer.get_feature_names_out())


from scipy.sparse import hstack

x_train_tfidf = hstack((x_train_tfidf, extra_train))
x_test_tfidf = hstack((x_test_tfidf, extra_test))

print(x_train_tfidf.shape)
print(x_test_tfidf.shape)


model = SVC(probability=True)

model.fit(x_train_tfidf, y_train)

y_pred = model.predict(x_test_tfidf)
proba = model.predict_proba(x_test_tfidf)



accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

fake_score = proba[:, 1]

for i in range(5):

    print("ニュース本文:")
    print(x_test.iloc[i][:200])

    print()

    if y_pred[i] == 1:
        label = "Fake"
    else:
        label = "Real"

    print("判定:", label)

    print(
        "フェイクニュースらしさ:",
        round(fake_score[i] * 100, 2),
        "%"
    )

    print("-" * 50)

from sklearn.metrics import confusion_matrix
from sklearn.metrics import ConfusionMatrixDisplay

cm = confusion_matrix(
    y_test,
    y_pred,
    normalize="true"
)

disp = ConfusionMatrixDisplay(confusion_matrix=cm)

disp.plot()