# -*- coding: utf-8 -*-
"""デザイン総合演習.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G9z_Qno4tHP3Ur41DAHIsPvBi5PcSSSR
"""

# pip install scikit-learn matplotlib scipy fugashi tqdm
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.svm import SVC
from sklearn.svm import LinearSVC
from sklearn.calibration import CalibratedClassifierCV

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import ConfusionMatrixDisplay

import matplotlib.pyplot as plt
from scipy.sparse import hstack

import fugashi
from fugashi import GenericTagger

from tqdm import tqdm

import re
import numpy as np

from sklearn.preprocessing import StandardScaler


tagger = fugashi.GenericTagger('-r "C:\\Program Files\\MeCab\\etc\\mecabrc" -d "C:\\Program Files\\MeCab\\dic\\ipadic"')
df = pd.read_csv(
    "fakenews.csv",
    encoding="utf-8"
)

print(df.head())

# 日本語解析(MeCab)
def mecab_tokenizer(text):
    pbar.update(1)
    tokens = []
    for word in tagger(text):
        pos = word.feature[0]
        surface = word.surface
        # 品詞フィルタ・数字除外・記号除外
        if (
            # surface
            pos in ["名詞", "動詞", "形容詞"]
            # pos == "名詞"
            and len(surface) > 1
            and not re.fullmatch(r'[0-9０-９]+', surface)
            and not re.fullmatch(r'[^\w\u3040-\u30FF\u4E00-\u9FFF]+', surface)):
            tokens.append(surface)
    return tokens


# 独自変数
# ここに定義していく

# "!"の数
def exclamation_count(text):
    return text.count("!")

# 曖昧表現
def ambiguity_count(text):
    ambiguous = ["かもしれない", "と思われる", "らしい", "のようだ", "といわれている", "可能性がある", "だろう"]
    return sum(text.count(a) for a in ambiguous)

# 記号の数
def symbol_count(text):
    return len(re.findall(r'[^\w\u3040-\u30FF\u4E00-\u9FFF\s]', text))

# 分の長さ
def text_length(text):
    return len(text)

# 数字の割合
def digit_ratio(text):
    digits = sum(c.isdigit() for c in text)
    return digits / max(len(text),1)

tagger = GenericTagger()

# text = "トヨタは東京都で新車を発表した"
# for word in tagger(text):
    # print(word.surface, word.feature)

# 固有名詞の割合
def proper_noun_ratio(text):
    words = list(tagger(str(text)))

    total = len(words)
    proper = 0

    for word in words:
        features = word.feature

        try:
            if features[0] == "名詞" and features[1] == "固有名詞":
                proper += 1
        except:
            pass

    return proper / total if total > 0 else 0

# 一文の長さの平均
def avg_sentence_length(text):
    sentences = re.split(r'[。！？]', text)
    sentences = [s for s in sentences if s]
    if len(sentences)==0:
        return 0
    return sum(len(s) for s in sentences)/len(sentences)

# 名詞割合
def noun_ratio(text):
    words = list(tagger(str(text)))

    total = len(words)
    noun = 0

    for word in words:
        if word.feature[0] == "名詞":
            noun += 1

    return noun / max(total, 1)

# 文の数
def sentence_count(text):
    return len([s for s in re.split(r'[。！？]', text) if s])

# 漢字率
def kanji_ratio(text):
    kanji = len(re.findall(r'[一-龯]', text))
    return kanji / max(len(text), 1)

# ひらがな率
def hiragana_ratio(text):
    hira = len(re.findall(r'[ぁ-ん]', text))
    return hira / max(len(text), 1)

df["exclamation_count"] = df["context"].apply(exclamation_count)
df["ambiguity_count"] = df["context"].apply(ambiguity_count)
df["symbol_count"] = df["context"].apply(symbol_count)
df["text_length"] = df["context"].apply(text_length)
df["digit_ratio"] = df["context"].apply(digit_ratio)
df["proper_noun_ratio"] = df["context"].apply(proper_noun_ratio)
df["avg_sentence_length"] = df["context"].apply(avg_sentence_length) 
df["noun_ratio"] = df["context"].apply(noun_ratio)
df["sentence_count"] = df["context"].apply(sentence_count)
df["kanji_ratio"] = df["context"].apply(kanji_ratio)
df["hiragana_ratio"] = df["context"].apply(hiragana_ratio)

# df[""] = df[""].apply()


print(df.groupby("isfake")[[
    "exclamation_count", 
    "ambiguity_count",
    "symbol_count",
    "text_length",
    "digit_ratio",
    "proper_noun_ratio",
    "avg_sentence_length",
    ]].mean())

print("proper_noun_ratio:")
print(df.groupby("isfake")["proper_noun_ratio"].describe())
print("\ndigit_ratio:")
print(df.groupby("isfake")["digit_ratio"].describe())
print("\navg_sentence_length:")
print(df.groupby("isfake")["avg_sentence_length"].describe())
print("\nkanji_ratio:")
print(df.groupby("isfake")["kanji_ratio"].describe())
print("\nhiragana_ratio:")
print(df.groupby("isfake")["hiragana_ratio"].describe())

feature_colums = [
    "exclamation_count",
    "ambiguity_count",
    "symbol_count",
    "text_length",
    "digit_ratio",
    "proper_noun_ratio",
    "avg_sentence_length",
    "noun_ratio",
    "sentence_count",
    "kanji_ratio",
    "hiragana_ratio",
    # ここに追加
]

x = df["context"]
y = df["isfake"]

extra = df[feature_colums]

x_train, x_test, y_train, y_test, extra_train, extra_test = train_test_split(
    x,
    y,
    extra,
    test_size=0.2,
    random_state=42
)

# 独自特徴量を標準化
scaler = StandardScaler()

extra_train_scaled = scaler.fit_transform(extra_train)
extra_test_scaled = scaler.transform(extra_test)

print(df["isfake"].value_counts())
print(y_train.value_counts())
print(y_test.value_counts())


pbar = tqdm(total=len(x_train), desc="MeCab処理")

vectorizer = TfidfVectorizer(
    max_features = 10000,
    tokenizer=mecab_tokenizer,
    token_pattern=None,
    min_df = 3,
    ngram_range=(1,2),
    sublinear_tf=True
)

x_train_tfidf = vectorizer.fit_transform(x_train)

print(vectorizer.get_feature_names_out())

print(vectorizer.get_feature_names_out()[:50])

x_test_tfidf = vectorizer.transform(x_test)

# print(vectorizer.get_feature_names_out())

# TF-IDFのみの場合OFF
# x_train_tfidf = hstack((x_train_tfidf, extra_train_scaled))
# x_test_tfidf = hstack((x_test_tfidf, extra_test_scaled))


print(x_train_tfidf.shape)
print(x_test_tfidf.shape)

print("標準化後の平均")
print(extra_train_scaled.mean(axis=0))

print("標準化後の標準偏差")
print(extra_train_scaled.std(axis=0))

base_model = LinearSVC(
    class_weight="balanced",
    random_state=42,
    max_iter=20000,
    C=1
)

model = CalibratedClassifierCV(
    base_model,
    cv=3
)
# model = SVC(kernel="linear", probability=True, class_weight="balanced")

# model.fit(x_train_tfidf, y_train)

# 独自特徴量だけ
model.fit(extra_train_scaled, y_train)

# y_pred = model.predict(x_test_tfidf)

# 独自特徴量だけ
y_pred = model.predict(extra_test_scaled)

print(pd.Series(y_pred).value_counts())
print(model.classes_)

proba = model.predict_proba(extra_test_scaled)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

fake_score = proba[:, 1] + proba[:, 2]  # クラス3がないので1+2

actual_map = {0: "Real", 1: "Fake", 2: "Fake"}

for i in range(5):

    print("ニュース本文:")
    print(x_test.iloc[i][:200])
    print()

    if y_pred[i] == 0:
        label = "Real"
    else:
        label = "Fake"

    real_score = round((1 - fake_score[i]) * 100, 2)

    print(f"判定: {label}")
    print(f"信頼度: {real_score}%（0=フェイク、100=リアル）")
    print(f"正解: {actual_map[y_test.iloc[i]]}")
    print("-" * 50)

cm = confusion_matrix(
    y_test,
    y_pred,
    normalize="true"
)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm
)

disp.plot()
plt.savefig("confusion_matrix2.png", dpi=150, bbox_inches="tight")
plt.show()