# -*- coding: utf-8 -*-
"""デザイン総合演習.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G9z_Qno4tHP3Ur41DAHIsPvBi5PcSSSR
"""

# pip install scikit-learn matplotlib scipy fugashi tqdm
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import ConfusionMatrixDisplay

import matplotlib.pyplot as plt
from scipy.sparse import hstack

import fugashi

from tqdm import tqdm

tagger = fugashi.GenericTagger('-r "C:\\Program Files\\MeCab\\etc\\mecabrc" -d "C:\\Program Files\\MeCab\\dic\\ipadic"')
df = pd.read_csv(
    "fakenews_isfake0123.csv",
    encoding="utf-8"
)

print(df.head())

# 日本語解析(MeCab)
def mecab_tokenizer(text):
    pbar.update(1)
    tokens = []
    for word in tagger(text):
        surface = word.surface
        if surface:
            tokens.append(surface)
    return tokens

# 独自変数
# "!"の数
def exclamation_count(text):
    return text.count("!")
# 曖昧表現
def ambiguity_count(text):
    ambiguous = ["かもしれない", "と思われる", "らしい", "のようだ", "といわれている", "可能性がある", "だろう"]
    return sum(text.count(a) for a in ambiguous)

df["exclamation_count"] = df["context"].apply(exclamation_count)
df["ambiguity_count"] = df["context"].apply(ambiguity_count)

feature_colums = [
    "exclamation_count",
    "ambiguity_count",
]

x = df["context"]
y = df["isfake"]

extra = df[feature_colums]

x_train, x_test, y_train, y_test, extra_train, extra_test = train_test_split(
    x,
    y,
    extra,
    test_size=0.2,
    random_state=42
)

pbar = tqdm(total=len(x_train), desc="MeCab処理")

vectorizer = TfidfVectorizer(
    max_features = 5000,
    tokenizer=mecab_tokenizer,
    token_pattern=None
)

x_train_tfidf = vectorizer.fit_transform(x_train)

print(vectorizer.get_feature_names_out())

print(vectorizer.get_feature_names_out()[:50])

x_test_tfidf = vectorizer.transform(x_test)

print(vectorizer.get_feature_names_out())

x_train_tfidf = hstack((x_train_tfidf, extra_train))
x_test_tfidf = hstack((x_test_tfidf, extra_test))

print(x_train_tfidf.shape)
print(x_test_tfidf.shape)


model = SVC(probability=True)

model.fit(x_train_tfidf, y_train)

y_pred = model.predict(x_test_tfidf)
proba = model.predict_proba(x_test_tfidf)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

fake_score = proba[:, 1] + proba[:, 2] + proba[:, 3]

for i in range(5):

    print("ニュース本文:")
    print(x_test.iloc[i][:200])

    print()

    label_map = {0: "Real", 1: "一部AI生成", 2: "全部AI生成", 3: "AI生成嘘内容"}
    label = label_map[y_pred[i]]

    print("判定:", label)

    print(
        "フェイクニュースらしさ:",
        round(fake_score[i] * 100, 2),
        "%"
    )

    print("-" * 50)

cm = confusion_matrix(
    y_test,
    y_pred,
    normalize="true"
)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm
)

disp.plot()
plt.savefig("confusion_matrix.png", dpi=150, bbox_inches="tight")
plt.show()